/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PruebaExamen;
import GUI.PendingBadConsequenceView;
import PruebaExamen.ControladorP5;
import NapakalakiGame.TreasureKind;
import java.util.ArrayList;

/**
 *
 * @author Laura
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private ControladorP5 controlModel;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        identificacion = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        dni = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        hiddentreasures = new javax.swing.JPanel();
        helmet = new javax.swing.JButton();
        armor = new javax.swing.JButton();
        onehand = new javax.swing.JButton();
        bothhands = new javax.swing.JButton();
        shoes = new javax.swing.JButton();
        badConsequence = new javax.swing.JPanel();
        DBConsequence = new javax.swing.JButton();
        NBConssequence = new javax.swing.JButton();
        SBConsequence = new javax.swing.JButton();
        pendingBadConsequence = new javax.swing.JPanel();
        ajustar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        identificacion.setText("Identificación");
        identificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                identificacionMouseClicked(evt);
            }
        });

        nombre.setText(" ");

        dni.setText(" ");

        salir.setText("Salir");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });

        hiddentreasures.setBorder(javax.swing.BorderFactory.createTitledBorder("Tesoros ocultos"));

        helmet.setText("HELMET");
        helmet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helmetMouseClicked(evt);
            }
        });

        armor.setText("ARMOR");
        armor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                armorMouseClicked(evt);
            }
        });

        onehand.setText("ONE HAND");
        onehand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onehandMouseClicked(evt);
            }
        });

        bothhands.setText("BOTH HANDS");
        bothhands.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bothhandsMouseClicked(evt);
            }
        });

        shoes.setText("SHOES");
        shoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shoesMouseClicked(evt);
            }
        });

        badConsequence.setBorder(javax.swing.BorderFactory.createTitledBorder("Bad Consequence"));

        DBConsequence.setText("Death");
        DBConsequence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DBConsequenceMouseClicked(evt);
            }
        });

        NBConssequence.setText("Numeric");
        NBConssequence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NBConssequenceMouseClicked(evt);
            }
        });

        SBConsequence.setText("Specific");
        SBConsequence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SBConsequenceMouseClicked(evt);
            }
        });

        pendingBadConsequence.setBorder(javax.swing.BorderFactory.createTitledBorder("Adjusted Bad Consequence"));

        ajustar.setText("Adjust");
        ajustar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajustarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hiddentreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ajustar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(DBConsequence)
                                .addGap(18, 18, 18)
                                .addComponent(NBConssequence)
                                .addGap(18, 18, 18)
                                .addComponent(SBConsequence))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(helmet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(armor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(onehand)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bothhands)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(shoes)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(badConsequence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pendingBadConsequence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 334, Short.MAX_VALUE)
                        .addComponent(salir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(identificacion)
                        .addComponent(nombre))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dni)
                        .addComponent(salir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hiddentreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helmet)
                    .addComponent(armor)
                    .addComponent(onehand)
                    .addComponent(bothhands)
                    .addComponent(shoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(badConsequence, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DBConsequence)
                    .addComponent(NBConssequence)
                    .addComponent(SBConsequence))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pendingBadConsequence, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ajustar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void identificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_identificacionMouseClicked
        nombre.setText("Jose Antonio Álvarez Ocete");
        dni.setText("77553417Q");
        repaint();
    }//GEN-LAST:event_identificacionMouseClicked

    private void helmetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helmetMouseClicked
        hiddentreasures.add(controlModel.getTreasure(TreasureKind.HELMET));
        repaint();
        revalidate();
    }//GEN-LAST:event_helmetMouseClicked

    private void armorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_armorMouseClicked
        hiddentreasures.add(controlModel.getTreasure(TreasureKind.ARMOR));
        repaint();
        revalidate();
    }//GEN-LAST:event_armorMouseClicked

    private void onehandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onehandMouseClicked
        hiddentreasures.add(controlModel.getTreasure(TreasureKind.ONEHAND));
        repaint();
        revalidate();
    }//GEN-LAST:event_onehandMouseClicked

    private void bothhandsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bothhandsMouseClicked
        hiddentreasures.add(controlModel.getTreasure(TreasureKind.BOTHHANDS));
        repaint();
        revalidate();
    }//GEN-LAST:event_bothhandsMouseClicked

    private void shoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shoesMouseClicked
        hiddentreasures.add(controlModel.getTreasure(TreasureKind.SHOE));
        repaint();
        revalidate();
    }//GEN-LAST:event_shoesMouseClicked

    private void DBConsequenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DBConsequenceMouseClicked
        badConsequence.add(controlModel.getDeathBadConsequence());
        repaint();
        revalidate();
    }//GEN-LAST:event_DBConsequenceMouseClicked

    private void NBConssequenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NBConssequenceMouseClicked
        badConsequence.add(controlModel.getNumericBadConsequence());
        repaint();
        revalidate();
    }//GEN-LAST:event_NBConssequenceMouseClicked

    private void SBConsequenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SBConsequenceMouseClicked
        // TODO add your handling code here:
        badConsequence.add(controlModel.getSpecificBadConsequence());
        repaint();
        revalidate();
    }//GEN-LAST:event_SBConsequenceMouseClicked

    private void ajustarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajustarMouseClicked
        ArrayList<PendingBadConsequenceView> array = controlModel.adjust();
        for(PendingBadConsequenceView pendingView: array) {
            pendingBadConsequence.add(pendingView);
        }
        repaint();
        revalidate();
    }//GEN-LAST:event_ajustarMouseClicked

    public void setControlador(ControladorP5 c){
        controlModel=c;
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DBConsequence;
    private javax.swing.JButton NBConssequence;
    private javax.swing.JButton SBConsequence;
    private javax.swing.JButton ajustar;
    private javax.swing.JButton armor;
    private javax.swing.JPanel badConsequence;
    private javax.swing.JButton bothhands;
    private javax.swing.JLabel dni;
    private javax.swing.JButton helmet;
    private javax.swing.JPanel hiddentreasures;
    private javax.swing.JButton identificacion;
    private javax.swing.JLabel nombre;
    private javax.swing.JButton onehand;
    private javax.swing.JPanel pendingBadConsequence;
    private javax.swing.JButton salir;
    private javax.swing.JButton shoes;
    // End of variables declaration//GEN-END:variables
}
